# Github serves all files in this repository through Jekyll (even if we don't use it).
# This configuration tells Jekyll not to ignore these folders.
include:
  - "_static"
  - "_sources"
  - "_images"